name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build
        run: npm run build
      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v0.1.0
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_PAT: ${{ secrets.GITHUB_PAT }}


